name: Build & Deploy

on:
    workflow_dispatch:

jobs:
    build:
        name: Build & Deploy
        runs-on: ubuntu-latest
        permissions:
            contents: 'read'
            id-token: 'write'

        steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Google Auth
          id: auth
          uses: 'google-github-actions/auth@v2'
          with:
            token_format: 'access_token'
            workload_identity_provider: '${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}'
            service_account: '${{ secrets.SERVICE_ACCOUNT_EMAIL }}'
        - name: Build, tag and push container
          id: build-image
          uses: docker/build-push-action@v6
          with:
            context: ${{ vars.code_directory }}
            push: true
            tags: gcr.io/mailiner-net/ws-tcp-proxy:${{ inputs.ref }}

        - name: Deploy to Cloud Run
          id: deploy
          uses: google-github-actions/deploy-cloudrun@v2
          with:
            project_id: ${{ vars.GCP_PROJECT_ID }}
            service: ${{ vars.GCP_SERVICE_NAME }}
            region: ${{ vars.GCP_REGION }}
            secrets: |
                MAILINER_PASETO_SECRET=MAILINER_PASETO_SECRET
            image: gcr.io/mailiner-net/ws-tcp-proxy:${{ inputs.ref }}

        - name: Update DNS
          run: |
            curl --request PUT \
                 --url https://api.cloudflare.com/client/v4/zones/${{ secrets.CF_DNS_ZONE_ID }}/dns_records/${{ secrets.CF_DNS_RECORD_ID }}\
                 --header 'Content-Type: application/json' \
                 --header 'X-Auth-Email: ${{ secrets.CLOUDFLARE_EMAIL }}' \
                 --header 'X-Auth-Key: ${{ secrets.CLOUDFLARE_TOKEN }}' \
                 --data '{
                    "content": "${{ steps.deploy.outputs.url }}",
                    "name": "proxy.mailiner.net",
                    "proxied": false,
                    "type": "CNAME",
                    "ttl": 600,
                    "id": ${{ secrets.CF_DNS_RECORD_ID }}
                 }'